package kr.co.infovine.dkmm.mapper.file;

import java.util.List;
import kr.co.infovine.dkmm.db.model.file.TFileSubModel;

public interface TFileSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_sub
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    int deleteByPrimaryKey(Integer fileSubSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_sub
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    int insert(TFileSubModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_sub
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    TFileSubModel selectByPrimaryKey(Integer fileSubSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_sub
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    List<TFileSubModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_sub
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    int updateByPrimaryKey(TFileSubModel row);
}