package kr.co.infovine.dkmm.db.model.define;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class TDefineNameStop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_name_stop.stop_seq
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    private int stopSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_name_stop.nick_name
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_name_stop.ins_seq
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    private int insSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_name_stop.ins_dt
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
    private Date insDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_name_stop.upt_seq
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    private int uptSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_name_stop.upt_dt
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
    private Date uptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_name_stop.use_yn
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    private String useYn;
    
    
    private String rowNum;
	
	//조건
	private String searchText;
	private String searchStartDt;
	private String searchEndDt;

}