package kr.co.infovine.dkmm.db.model.file;

import java.util.Date;

public class TFileSubModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.file_sub_seq
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private Integer fileSubSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.file_uuid_sub
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private String fileUuidSub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.file_nm
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private String fileNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.file_save_nm
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private String fileSaveNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.file_size
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private String fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.del_yn
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private String delYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.ins_seq
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private Long insSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.ins_dt
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private Date insDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_sub.file_sub_seq
     *
     * @return the value of t_file_sub.file_sub_seq
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public Integer getFileSubSeq() {
        return fileSubSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_sub.file_sub_seq
     *
     * @param fileSubSeq the value for t_file_sub.file_sub_seq
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public void setFileSubSeq(Integer fileSubSeq) {
        this.fileSubSeq = fileSubSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_sub.file_uuid_sub
     *
     * @return the value of t_file_sub.file_uuid_sub
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public String getFileUuidSub() {
        return fileUuidSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_sub.file_uuid_sub
     *
     * @param fileUuidSub the value for t_file_sub.file_uuid_sub
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public void setFileUuidSub(String fileUuidSub) {
        this.fileUuidSub = fileUuidSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_sub.file_nm
     *
     * @return the value of t_file_sub.file_nm
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public String getFileNm() {
        return fileNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_sub.file_nm
     *
     * @param fileNm the value for t_file_sub.file_nm
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public void setFileNm(String fileNm) {
        this.fileNm = fileNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_sub.file_save_nm
     *
     * @return the value of t_file_sub.file_save_nm
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public String getFileSaveNm() {
        return fileSaveNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_sub.file_save_nm
     *
     * @param fileSaveNm the value for t_file_sub.file_save_nm
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public void setFileSaveNm(String fileSaveNm) {
        this.fileSaveNm = fileSaveNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_sub.file_size
     *
     * @return the value of t_file_sub.file_size
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_sub.file_size
     *
     * @param fileSize the value for t_file_sub.file_size
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_sub.del_yn
     *
     * @return the value of t_file_sub.del_yn
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public String getDelYn() {
        return delYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_sub.del_yn
     *
     * @param delYn the value for t_file_sub.del_yn
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public void setDelYn(String delYn) {
        this.delYn = delYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_sub.ins_seq
     *
     * @return the value of t_file_sub.ins_seq
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public Long getInsSeq() {
        return insSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_sub.ins_seq
     *
     * @param insSeq the value for t_file_sub.ins_seq
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public void setInsSeq(Long insSeq) {
        this.insSeq = insSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_sub.ins_dt
     *
     * @return the value of t_file_sub.ins_dt
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public Date getInsDt() {
        return insDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_sub.ins_dt
     *
     * @param insDt the value for t_file_sub.ins_dt
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    public void setInsDt(Date insDt) {
        this.insDt = insDt;
    }
}