package kr.co.infovine.dkmm.db.model.file;

import java.util.Date;

public class TFileModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.file_seq
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    private Integer fileSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.file_uuid
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    private String fileUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.page_type
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    private String pageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.user_ip
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    private String userIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.del_yn
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    private String delYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.ins_seq
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    private Long insSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.ins_dt
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    private Date insDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.file_seq
     *
     * @return the value of t_file.file_seq
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public Integer getFileSeq() {
        return fileSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.file_seq
     *
     * @param fileSeq the value for t_file.file_seq
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public void setFileSeq(Integer fileSeq) {
        this.fileSeq = fileSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.file_uuid
     *
     * @return the value of t_file.file_uuid
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public String getFileUuid() {
        return fileUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.file_uuid
     *
     * @param fileUuid the value for t_file.file_uuid
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public void setFileUuid(String fileUuid) {
        this.fileUuid = fileUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.page_type
     *
     * @return the value of t_file.page_type
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public String getPageType() {
        return pageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.page_type
     *
     * @param pageType the value for t_file.page_type
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public void setPageType(String pageType) {
        this.pageType = pageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.user_ip
     *
     * @return the value of t_file.user_ip
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.user_ip
     *
     * @param userIp the value for t_file.user_ip
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.del_yn
     *
     * @return the value of t_file.del_yn
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public String getDelYn() {
        return delYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.del_yn
     *
     * @param delYn the value for t_file.del_yn
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public void setDelYn(String delYn) {
        this.delYn = delYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.ins_seq
     *
     * @return the value of t_file.ins_seq
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public Long getInsSeq() {
        return insSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.ins_seq
     *
     * @param insSeq the value for t_file.ins_seq
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public void setInsSeq(Long insSeq) {
        this.insSeq = insSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.ins_dt
     *
     * @return the value of t_file.ins_dt
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public Date getInsDt() {
        return insDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.ins_dt
     *
     * @param insDt the value for t_file.ins_dt
     *
     * @mbg.generated Thu Dec 15 15:23:16 KST 2022
     */
    public void setInsDt(Date insDt) {
        this.insDt = insDt;
    }
}