package kr.co.infovine.dkmm.db.model.file;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class TFileSubModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.file_sub_seq
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private Integer fileSubSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.file_uuid_sub
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private String fileUuidSub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.file_nm
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private String fileNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.file_save_nm
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private String fileSaveNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.file_size
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private String fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.del_yn
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private String delYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.ins_seq
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private int insSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_sub.ins_dt
     *
     * @mbg.generated Thu Dec 15 15:23:24 KST 2022
     */
    private Date insDt;
}