package kr.co.infovine.dkmm.db.model.userLeave;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;
@Getter
@Setter
public class TUserLeave {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_leave.leave_seq
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    private Integer leaveSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_leave.user_seq
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    private Long userSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_leave.reason
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_leave.ins_dt
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    private String insDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_leave.approval_yn
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    private String approvalYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_leave.upt_seq
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    private Long uptSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_leave.upt_dt
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    private Date uptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_leave.ins_seq
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    private Long insSeq;
    
    //조건
	private String searchText;
	private String searchStartDt;
	private String searchEndDt;

    
    //추가
    private String rowNum;
    private String nickName;
    private String userId;
    private String delYn;
}