package kr.co.infovine.dkmm.mapper.userLeave;

import java.util.List;

import kr.co.infovine.dkmm.db.model.user.TUserInfo;
import kr.co.infovine.dkmm.db.model.userLeave.TUserLeave;

public interface TUserLeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_leave
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    int deleteByPrimaryKey(Integer leaveSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_leave
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    int insert(TUserLeave row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_leave
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    TUserLeave selectByPrimaryKey(Integer leaveSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_leave
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    List<TUserLeave> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_leave
     *
     * @mbg.generated Mon Dec 05 09:42:32 KST 2022
     */
    int updateByPrimaryKey(TUserLeave row);
    
    //탈퇴회원정보 조회
    List<TUserLeave> selectAllUserLeave(TUserLeave userLeave);
   //탈퇴회원정보 상세보기
    TUserLeave selectUserLeaveDetail(TUserLeave userLeave);

}