package kr.co.infovine.dkmm.mapper.store;

import java.util.List;
import kr.co.infovine.dkmm.db.model.store.TStoreAddressTest;

public interface TStoreAddressTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_address_test
     *
     * @mbg.generated Tue Nov 22 16:54:52 KST 2022
     */
    int insert(TStoreAddressTest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_address_test
     *
     * @mbg.generated Tue Nov 22 16:54:52 KST 2022
     */
    List<TStoreAddressTest> selectAll();
}