package kr.co.infovine.dkmm.mapper.store;

import java.util.List;
import kr.co.infovine.dkmm.db.model.store.TStoreInfoOrg;

public interface TStoreInfoOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info_org
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    int insert(TStoreInfoOrg row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info_org
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    List<TStoreInfoOrg> selectAll();
    
    /* STORE_ORG 신규 작업 Data 카운트 : process_yn = 'N'  */
    int selectProcCount();
    
    /* STORE_ORG 영업중 상점 process_yn update  */
	int updateStoreOrgStatus01();
	
	/* STORE_ORG 폐업 상점 process_yn update  */
	int updateStoreOrgStatus02();
	
	/* STORE_ORG 엑셀 상점 update  */
	int bulkInsert(List<TStoreInfoOrg> row);
}