package kr.co.infovine.dkmm.mapper.store;

import java.util.List;
import kr.co.infovine.dkmm.db.model.store.TStoreAddress;

public interface TStoreAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_address
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    int insert(TStoreAddress row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_address
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    List<TStoreAddress> selectAll();
}