package kr.co.infovine.dkmm.mapper.store;

import java.util.List;
import kr.co.infovine.dkmm.db.model.store.TStoreInfoModel;

public interface TStoreInfoMapper {
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info
     *
     * @mbg.generated Tue Nov 22 16:17:09 KST 2022
     */
	List<TStoreInfoModel> selectAll();
    
	//매장정보 조회
	List<TStoreInfoModel> selectStoreInfo(TStoreInfoModel storeInfo);
    //매장정보 상세보기
    TStoreInfoModel selectDetail(TStoreInfoModel storeInfo);
    //매장정보 등록
	void insertStoreInfo(TStoreInfoModel storeInfo);
    
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info
     *
     * @mbg.generated Tue Nov 22 16:17:09 KST 2022
     */
    int deleteByPrimaryKey(int storeSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info
     *
     * @mbg.generated Tue Nov 22 16:17:09 KST 2022
     */
    int insert(TStoreInfoModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info
     *
     * @mbg.generated Tue Nov 22 16:17:09 KST 2022
     */
    TStoreInfoModel selectByPrimaryKey(int storeSeq);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info
     *
     * @mbg.generated Tue Nov 22 16:17:09 KST 2022
     */
    int updateByPrimaryKey(TStoreInfoModel row);
    
    /* STORE_INFO 정보 update  */
	int mergeStoreInfo();	
	
	/* STORE_INFO 폐업 상점 update  */
	int updateCloseStoreInfo();	
	
	/* STORE_INFO '카페' 카테고리 기준 업데이트  */
	int updateCafeCtgry();
	
	/* STORE_INFO '카페' 상호명 기준 업데이트  */
	int updateCafeName();
	
	
	/* STORE_INFO - 좌표값 없는 Data 조회  */
	List<TStoreInfoModel> selectNonExistLatitude();
	
	int updateRoadAddrByPrimaryKey(TStoreInfoModel storeInfo);
	
	int updateFailVworldByPrimaryKey(TStoreInfoModel storeInfo);
	
	List<TStoreInfoModel> selectStoreExcel(TStoreInfoModel storeInfo);
	
	int selectStoreCount(TStoreInfoModel storeInfo);
	
}