package kr.co.infovine.dkmm.mapper.store;

import java.util.List;
import kr.co.infovine.dkmm.db.model.store.TStoreInfoModel;

public interface TStoreInfoMapper {
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info
     *
     * @mbg.generated Tue Nov 22 16:17:09 KST 2022
     */
	List<TStoreInfoModel> selectAll();
    
	//매장정보 조회
	List<TStoreInfoModel> selectStoreInfo(TStoreInfoModel storeInfo);
    //매장정보 상세보기
    TStoreInfoModel selectDetail(TStoreInfoModel storeInfo);
    //매장정보 등록
	void insertStoreInfo(TStoreInfoModel storeInfo);
    
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info
     *
     * @mbg.generated Tue Nov 22 16:17:09 KST 2022
     */
    int deleteByPrimaryKey(Long storeSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info
     *
     * @mbg.generated Tue Nov 22 16:17:09 KST 2022
     */
    int insert(TStoreInfoModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info
     *
     * @mbg.generated Tue Nov 22 16:17:09 KST 2022
     */
    TStoreInfoModel selectByPrimaryKey(Long storeSeq);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store_info
     *
     * @mbg.generated Tue Nov 22 16:17:09 KST 2022
     */
    int updateByPrimaryKey(TStoreInfoModel row);
    
    /* STORE_INFO 정보 update  */
	int mergeStoreInfo();	
	
	/* STORE_INFO 폐업 상점 update  */
	int updateCloseStoreInfo();	
}