package kr.co.infovine.dkmm.mapper.store;

import kr.co.infovine.dkmm.db.model.store.TStoreGooglePlaceModel;

import java.util.List;

public interface TStoreGooglePlaceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_store_google_place
	 * @mbg.generated  Wed Sep 14 15:13:28 KST 2022
	 */
	int deleteByPrimaryKey(String placeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_store_google_place
	 * @mbg.generated  Wed Sep 14 15:13:28 KST 2022
	 */
	int insert(TStoreGooglePlaceModel row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_store_google_place
	 * @mbg.generated  Wed Sep 14 15:13:28 KST 2022
	 */
	List<TStoreGooglePlaceModel> selectByPrimaryKey(TStoreGooglePlaceModel row);
	
	List<TStoreGooglePlaceModel> selectByLikeStoreName(TStoreGooglePlaceModel row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_store_google_place
	 * @mbg.generated  Wed Sep 14 15:13:28 KST 2022
	 */
	List<TStoreGooglePlaceModel> selectAll();

	List<TStoreGooglePlaceModel> selectAllExceptForStoreSeq();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_store_google_place
	 * @mbg.generated  Wed Sep 14 15:13:28 KST 2022
	 */
	int updateByPrimaryKey(TStoreGooglePlaceModel row);
}