package kr.co.infovine.dkmm.mapper.common;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import kr.co.infovine.dkmm.db.model.commoncode.CommonCodeModel;

public interface TbCommonCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Common_Code
     *
     * @mbg.generated Wed Jun 09 13:42:42 KST 2021
     */
    int deleteByPrimaryKey(@Param("codeGroup") String codeGroup, @Param("codeValue") String codeValue);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Common_Code
     *
     * @mbg.generated Wed Jun 09 13:42:42 KST 2021
     */
    int insert(CommonCodeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Common_Code
     *
     * @mbg.generated Wed Jun 09 13:42:42 KST 2021
     */
    CommonCodeModel selectByPrimaryKey(@Param("codeGroup") String codeGroup, @Param("codeValue") String codeValue);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Common_Code
     *
     * @mbg.generated Wed Jun 09 13:42:42 KST 2021
     */
    List<CommonCodeModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Common_Code
     *
     * @mbg.generated Wed Jun 09 13:42:42 KST 2021
     */
    int updateByPrimaryKey(CommonCodeModel record);

    //코드그룹 불러오기
    List<CommonCodeModel> selectByCodeGroup(CommonCodeModel codeGroup);
}