package kr.co.infovine.dkmm.db.model.store;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class TStoreAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.store_seq
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private Integer storeSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.old_zip
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private String oldZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.old_addr
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private String oldAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.road_zip
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private String roadZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.road_addr
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private String roadAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.road_addr_detail1
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private String roadAddrDetail1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.road_addr_detail2
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private String roadAddrDetail2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.road_addr_detail3
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private String roadAddrDetail3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.road_addr_detail4
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private String roadAddrDetail4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.road_addr_detail5
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private String roadAddrDetail5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_address.road_addr_detail6
     *
     * @mbg.generated Tue Nov 22 16:54:44 KST 2022
     */
    private String roadAddrDetail6;
}