package kr.co.infovine.dkmm.db.model.store;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class TStoreInfoOrgExcel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.seq
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.service_nm
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String serviceNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.service_id
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.area_code
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.manage_no
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String manageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.approval_dt
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String approvalDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.cancel_dt
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String cancelDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.status_type
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String statusType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.status_nm
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String statusNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.status_code
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String statusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.status_nm2
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String statusNm2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.close_dt
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String closeDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.holiday_start_dt
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String holidayStartDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.holiday_end_dt
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String holidayEndDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.reopen_dt
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String reopenDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.tel
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.area_size
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String areaSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.zip
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.addr
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.road_addr
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String roadAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.road_zip
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String roadZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.store_nm
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String storeNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.upt_dt
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String uptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.sql_type
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String sqlType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.data_upt_dt
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String dataUptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.ctgry_nm
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String ctgryNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.position_x
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String positionX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.position_y
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String positionY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.ctgry_nm2
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String ctgryNm2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.man_cnt
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String manCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.woman_cnt
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String womanCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.area_type
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String areaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.degree_type
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String degreeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.water_type
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String waterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.person_cnt1
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String personCnt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.person_cnt2
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String personCnt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.person_cnt3
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String personCnt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.person_cnt4
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String personCnt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.person_cnt5
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String personCnt5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.store_buy_type
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String storeBuyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.store_money
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String storeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.store_month_money
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String storeMonthMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.many_use_yn
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String manyUseYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.area_tot
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String areaTot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.culture_no
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String cultureNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.culture_menu
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String cultureMenu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.hompage
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String hompage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_org.process_yn
     *
     * @mbg.generated Tue Nov 22 16:51:41 KST 2022
     */
    private String processYn;
}