package kr.co.infovine.dkmm.db.model.store;

import java.util.Date;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class TStoreInfoModelTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.store_seq
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private Long storeSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.store_mngt_no
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String storeMngtNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.store_nm
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String storeNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.ctgry_nm
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String ctgryNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.road_addr
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String roadAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.zip
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String roadZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.latitude
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.longitude
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.company_no
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String companyNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.store_open_time
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String storeOpenTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.store_end_time
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String storeEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.store_holiday_type
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String storeHolidayType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.max_cnt
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String maxCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.file_uuid
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String fileUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.use_yn
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.del_yn
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String delYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.ins_seq
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private Long insSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.ins_dt
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private Date insDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.upt_seq
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private Long uptSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.upt_dt
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private Date uptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.store_tel
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String storeTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.area_tot
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String areaTot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.priority
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.like_cnt
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private Long likeCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.last_wait_user_seq
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private Long lastWaitUserSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.last_wait_person_cnt
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private Integer lastWaitPersonCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.last_wait_ins_dt
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private Date lastWaitInsDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.old_addr
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String oldAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store_info_test.old_zip
     *
     * @mbg.generated Tue Nov 22 16:52:13 KST 2022
     */
    private String oldZip;
    
    private String roadAddrDetail1;
	private String roadAddrDetail2;
	private String roadAddrDetail3;
	private String roadAddrDetail4;
	private String roadAddrDetail5;
	private String roadAddrDetail6;
}