package kr.co.infovine.dkmm.mapper.marketing;

import java.util.List;

import kr.co.infovine.dkmm.db.model.faq.TFaq;
import kr.co.infovine.dkmm.db.model.marketing.TMarketingAnalysis;

public interface TMarketingAnalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_marketing_analysis
     *
     * @mbg.generated Mon Dec 12 16:19:04 KST 2022
     */
    int deleteByPrimaryKey(Integer marketingSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_marketing_analysis
     *
     * @mbg.generated Mon Dec 12 16:19:04 KST 2022
     */
    int insert(TMarketingAnalysis row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_marketing_analysis
     *
     * @mbg.generated Mon Dec 12 16:19:04 KST 2022
     */
    TMarketingAnalysis selectByPrimaryKey(Integer marketingSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_marketing_analysis
     *
     * @mbg.generated Mon Dec 12 16:19:04 KST 2022
     */
    List<TMarketingAnalysis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_marketing_analysis
     *
     * @mbg.generated Mon Dec 12 16:19:04 KST 2022
     */
    int updateByPrimaryKey(TMarketingAnalysis row);
    
    //(월)유입통계
    List<TMarketingAnalysis> marketingMonthly(TMarketingAnalysis maketingAnalysis);
    
    //(주)가입통계
    List<TMarketingAnalysis> marketingWeekly(TMarketingAnalysis maketingAnalysis);
}