package kr.co.infovine.dkmm.mapper.faq;

import java.util.List;

import kr.co.infovine.dkmm.db.model.board.TBoard;
import kr.co.infovine.dkmm.db.model.faq.TFaq;

public interface TFaqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_faq
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    int deleteByPrimaryKey(Integer faqSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_faq
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    int insert(TFaq row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_faq
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    TFaq selectByPrimaryKey(Integer faqSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_faq
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    List<TFaq> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_faq
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    int updateByPrimaryKey(TFaq row);
    
    //FAQ 전체 조회
    List<TFaq> selectFaqAllList(TFaq faq);
    
    //FAQ 상세보기
    TFaq selectFaqDetail(TFaq faq);
    
    int deleteFaqFileData(TFaq faq);
}