package kr.co.infovine.dkmm.mapper.board;

import java.util.List;
import kr.co.infovine.dkmm.db.model.board.TBoard;

public interface TBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    int deleteByPrimaryKey(Integer boardSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    int insert(TBoard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    TBoard selectByPrimaryKey(Integer boardSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    List<TBoard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_board
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    int updateByPrimaryKey(TBoard row);
    
	//공지사항 전체 조회
	List<TBoard> selectboardAllList(TBoard board);
	//공지사항 상세보기
	TBoard selectBoardDetail(TBoard board);
	
	int deleteBoardFileData(TBoard row);
}