package kr.co.infovine.dkmm.db.model.admin;


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
public class TbAdminProgramModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_Program.admin_program_seq
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
	private Integer adminProgramSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_Program.program_id
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    private String programId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_Program.parents_program_id
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    private String parentsProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_Program.level
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_Program.program_name
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    private String programName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_Program.program_sort
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    private String programSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_Program.use_yn
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_Program.reg_date
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    private String regDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_Program.update_date
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    private String updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_Program.location
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    private String location;

    /**
     * 저장시 password를 체크하기 위함
     */
    private String password;
    
    private String rowNum;
	
	//조건
	private String searchText;
	private String searchStartDt;
	private String searchEndDt;
	
	private String searchLevel;
}