package kr.co.infovine.dkmm.db.model.admin;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
public class TbAdminUserLogModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User_Log.seq
     *
     * @mbg.generated Fri Jul 09 18:42:47 KST 2021
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User_Log.admin_user_seq
     *
     * @mbg.generated Fri Jul 09 18:42:47 KST 2021
     */
    @JsonIgnore
    private Integer adminUserSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User_Log.request_url
     *
     * @mbg.generated Fri Jul 09 18:42:47 KST 2021
     */
    private String requestUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User_Log.param
     *
     * @mbg.generated Fri Jul 09 18:42:47 KST 2021
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User_Log.reg_date
     *
     * @mbg.generated Fri Jul 09 18:42:47 KST 2021
     */
    private String regDate;
    
    private String startDate;
    
    private String closeDate;
    
    private TbAdminScaleDownUserModel tbAdminScaleDownUserModel;
}