package kr.co.infovine.dkmm.db.model.admin;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
public class TbAdminUserModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.admin_user_seq
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private Integer adminUserSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.user_id
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private String userId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column TB_Admin_User.user_id
    *
    * @mbg.generated Mon May 10 14:15:56 KST 2021
    */
   private String userName;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.password
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private String password;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.user_type_code
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private String userTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.reg_date
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private String regDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.update_date
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private String updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.password_error_count
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private Integer passwordErrorCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.password_error_date
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private String passwordErrorDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.password_lost_check
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private String passwordLostCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.password_lost_date
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private String passwordLostDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.lastlogin_date
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private String lastloginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_Admin_User.block_yn
     *
     * @mbg.generated Mon May 10 14:15:56 KST 2021
     */
    private String blockYn;

    /**
     * 새로운 패스워드 변경
     */
    private String oldPassword;
    
    private String newPassword1;
    
    private String newPassword2;
    
    private String authority;
    private String userTypeCodeNm;
    
  //조건
  	private String searchText;
  	private String searchStartDt;
  	private String searchEndDt;
}