package kr.co.infovine.dkmm.mapper.define;

import java.util.List;
import kr.co.infovine.dkmm.db.model.define.TDefineNameStop;

public interface TDefineNameStopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_define_name_stop
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    int deleteByPrimaryKey(int stopSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_define_name_stop
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    int insert(TDefineNameStop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_define_name_stop
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    TDefineNameStop selectByPrimaryKey(Integer stopSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_define_name_stop
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    List<TDefineNameStop> selectAll(TDefineNameStop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_define_name_stop
     *
     * @mbg.generated Mon Dec 05 16:17:43 KST 2022
     */
    int updateByPrimaryKey(TDefineNameStop row);
}