package kr.co.infovine.dkmm.mapper.admin;

import java.util.List;
import kr.co.infovine.dkmm.db.model.admin.TbAdminProgramModel;

public interface TAdminProgramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_Program
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    int deleteByPrimaryKey(Integer adminProgramSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_Program
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    int insert(TbAdminProgramModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_Program
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    TbAdminProgramModel selectByPrimaryKey(Integer adminProgramSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_Program
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    List<TbAdminProgramModel> selectAll(TbAdminProgramModel programMenu);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_Program
     *
     * @mbg.generated Mon May 10 14:15:22 KST 2021
     */
    int updateByPrimaryKey(TbAdminProgramModel record);
    
    TbAdminProgramModel selectNextProgramId(TbAdminProgramModel record);
}