package kr.co.infovine.dkmm.mapper.admin;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import kr.co.infovine.dkmm.db.model.admin.TbAdminUserLogModel;

public interface TAdminUserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_User_Log
     *
     * @mbg.generated Fri Jul 09 18:42:47 KST 2021
     */
    int insert(TbAdminUserLogModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_User_Log
     *
     * @mbg.generated Fri Jul 09 18:42:47 KST 2021
     */
    List<TbAdminUserLogModel> selectAll();
    
    
    List<TbAdminUserLogModel> selectByPrimaryKey(@Param("startDate") String startDate, @Param("closeDate") String closeDate);
}