package kr.co.infovine.dkmm.mapper.admin;

import java.util.List;
import kr.co.infovine.dkmm.db.model.admin.TbAdminPermissionModel;

/**
 * kr.co.infovine.dkmm.mapper.admin
 * TbAdminPermissionMapper.java
 * 2021-05-14 Made by Duhyun, Kim
 */
public interface TAdminPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_Permission
     *
     * @mbg.generated Mon May 10 14:15:37 KST 2021
     */
    int deleteByPrimaryKey(Integer adminPermissionSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_Permission
     *
     * @mbg.generated Mon May 10 14:15:37 KST 2021
     */
    int insert(TbAdminPermissionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_Permission
     *
     * @mbg.generated Mon May 10 14:15:37 KST 2021
     */
    TbAdminPermissionModel selectByPrimaryKey(Integer adminPermissionSeq);
    
    
    // region 설명: 좌측 메뉴 생성 LEFT JOIN 
    /**
     * 2021-05-14 Made by Duhyun, Kim
     * @param args
     * return : TbAdminPermission
     */
    List<TbAdminPermissionModel> selectByUserLeftMenu(Integer adminPermissionSeq);
    
    List<TbAdminPermissionModel> selectByUserLeftMenuTEST(Integer adminPermissionSeq);
    // end region    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_Permission
     *
     * @mbg.generated Mon May 10 14:15:37 KST 2021
     */
    List<TbAdminPermissionModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_Admin_Permission
     *
     * @mbg.generated Mon May 10 14:15:37 KST 2021
     */
    int updateByPrimaryKey(TbAdminPermissionModel record);
    
    
    // region 설명: 권한을 전체 삭제 한 뒤에 승인된 내용을 다시 밀어넣기 위함 
    /**
     * 2021-07-05 Made by Duhyun, Kim
     * @param args
     * return : int
     */
    int deleteByAdminUserSeq(int adminUserSeq);
    // end region
}