package kr.co.infovine.dkmm.db.model.user;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;
@Getter
@Setter
public class TUserInfo {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.user_seq
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private Integer userSeq;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.user_id
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String userId;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.user_type
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String userType;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.user_pw
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String userPw;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.user_name
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String userName;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.nick_name
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String nickName;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.gender
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String gender;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.email
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String email;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.phone
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String phone;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.tel
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String tel;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.birth
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String birth;
	
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.addr
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String addr;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.addr_detail
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String addrDetail;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.zip
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String zip;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.meno
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String meno;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.user_photo
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String userPhoto;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.last_time
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private Date lastTime;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.last_ip
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String lastIp;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.approval_yn
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String approvalYn;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.use_yn
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String useYn;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.del_yn
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String delYn;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.ins_seq
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private Long insSeq;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.ins_dt
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String insDt;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.ins_ip
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String insIp;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.upt_seq
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private Long uptSeq;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.upt_dt
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private Date uptDt;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.upt_ip
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String uptIp;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.access_token
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String accessToken;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.refresh_token
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String refreshToken;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.nick_seq
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private Long nickSeq;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.di
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String di;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.ci
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String ci;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.tel_type
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String telType;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.person_type
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String personType;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.approval_dt
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private Date approvalDt;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.market_yn
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String marketYn;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.os_type
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String osType;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.push_token
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String pushToken;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.sms_yn
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String smsYn;
	
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_info.inflow_channel
	 *
	 * @mbg.generated Tue Nov 22 17:05:02 KST 2022
	 */
	private String inflowChannel;
	
	// t_user_event
	private String point;
	private String coupon;
	private String category;
	private String eventSeq;
	private int waitCnt;
	private String likeCnt;
	
	//추가
	private String age;
	private String rowNum;
	
	//조건
	private String searchText;
	private String searchStartDt;
	private String searchEndDt;
}