package kr.co.infovine.dkmm.db.model.board;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.Getter;
import lombok.Setter;
@Getter
@Setter
public class TBoard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.board_seq
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    private int boardSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.board_div
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    private String boardDiv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.title
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.content
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.view_cnt
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    private int viewCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.file_uuid
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    private String fileUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.ins_seq
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    private int insSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.ins_dt
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
    private Date insDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.upt_seq
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    private int uptSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.upt_dt
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
    private Date uptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board.del_yn
     *
     * @mbg.generated Wed Dec 07 09:59:40 KST 2022
     */
    private String delYn;
    
    private String imageUrl;
    private String mainUrl;
    
    //조건
    private String searchText;
    private String searchStartDt;
    private String searchEndDt;
    private String type;
    
  	private String rowNum;
}