package kr.co.infovine.dkmm.db.model.nicknm;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.Getter;
import lombok.Setter;
@Getter
@Setter
public class TDefineNicknm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.nick_seq
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    private int nickSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.nick_nm
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    private String nickNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.nick_img
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    private String nickImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.work_seq
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    private int workSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.nick_comment
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    private String nickComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.del_yn
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    private String delYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.ins_seq
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    private int insSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.ins_dt
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
    private Date insDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.upt_seq
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    private int uptSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.upt_dt
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
    private Date uptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_define_nicknm.file_uuid
     *
     * @mbg.generated Fri Nov 25 11:29:08 KST 2022
     */
    private String fileUuid;
    
    //추가
    private String rowNum;
    private String workNm;
    private String fileNm;
    private String fileSaveNm;
    private String type;
    private String mainUrl;
    private String imageUrl;
    
    //조건
    private String searchText;
    private String searchType;
    private String searchStartDt;
    private String searchEndDt;
    
}