package kr.co.infovine.dkmm.db.model.faq;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.Getter;
import lombok.Setter;
@Getter
@Setter
public class TFaq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.faq_seq
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    private Integer faqSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.faq_div
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    private String faqDiv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.title
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.content
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.view_cnt
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    private Long viewCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.file_uuid
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    private String fileUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.ins_seq
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    private int insSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.ins_dt
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
    private Date insDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.upt_seq
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    private int uptSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.upt_dt
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
    private Date uptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_faq.del_yn
     *
     * @mbg.generated Thu Dec 08 17:45:02 KST 2022
     */
    private String delYn;
    
    //조건
    private String searchText;
    private String searchStartDt;
    private String searchEndDt;
    private String type;
    
    //file
    private String fileNm;
    private String fileSaveNm;
}