package kr.co.infovine.dkmm.db.model.commoncode;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CommonCodeModel {
	private int seq;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COMMON_CODE.code_group
	 * @mbg.generated  Thu May 27 17:35:27 KST 2021
	 */
	private String codeGroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COMMON_CODE.code_value
	 * @mbg.generated  Thu May 27 17:35:27 KST 2021
	 */
	private String codeValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COMMON_CODE.code_name
	 * @mbg.generated  Thu May 27 17:35:27 KST 2021
	 */
	private String codeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COMMON_CODE.code_description
	 * @mbg.generated  Thu May 27 17:35:27 KST 2021
	 */
	private String codeDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COMMON_CODE.reg_date
	 * @mbg.generated  Thu May 27 17:35:27 KST 2021
	 */
	private Date regDate;

	/**
	 * 수정삭제는 권한이 있는 사람만 할 수 있음
	 */
	private String password;
}